### ISSUE TITLE
What is 'settings'?

### ISSUE THREAD

**Issue by aniruddhamarathe** [bhartidk/centipede_diversity_endemism#1]
Hi Bharati,
What is settings in this line?
https://github.com/bhartidk/centipede_diversity_endemism/blob/1c4231c26feed8d24b4d3396286ab94dfcbce1b8/code3_sdm_enmeval_results_12Mar21.R#L207

 Is it a combination of column names in the results data frame? It does not appear anywhere earlier in the code

**Comment by bhartidk** [comment]
Hi Aniruddha,

The settings column specifies the model feature class and regularization parameter (eg. H_5, means that model contains only hinge feature, and uses a regularization parameter of 5). There are 60 models for a given species, given the different feature class x regularization parameter combinations.

Once the best model is selected, this line helps identify the id of the best model through its specific model settings. This id is used to pull out the specific enmeval model and extract results.

Just a general note - I atleast know of one update of the ENMeval package in R from the version I use here. I am told that the newer version has differences from the version I used, and might have more easy to use functions, which are not reflected in this code.

Regards,
Bharti

**Comment by aniruddhamarathe** [comment]
Hi Bharti,
Thank you for the response. I had imagined it will be some combination of the model fitting parameters. I think that column is now called 'tune.args'. Thanks.

**Comment by bhartidk** [comment]
Thanks for the question Aniruddha. I'll find better ways of including package version information in future work so that the code can be understood or replicated more seamlessly. 

Regards,
Bharti
